version: '3'

services:
  database:
    container_name: database
    platform: linux/x86_64
    image: mysql:8.0.26
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_HOST=database
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=db
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=password

  server:
    volumes:
      - ./dist:/usr/src/app/dist
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
      - ./db:/usr/src/app/db
      - ./package.json:/usr/src/app/package.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - ./tsconfig.migration.json:/usr/src/app/tsconfig.migration.json
    container_name: server
    profiles:
      - 'server'
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - database
    env_file:
      - ./docker/.env.local
